"""One source for every Kavenegar template.

Reads the automatic messages (server/internal/sms/auto.go) and the ready-made texts (web/src/lib/smsLibrary.ts) and writes:
  1. server/internal/sms/kvtemplates_gen.go   what the server sends (template name + text with {variables})
  2. sms-kavenegar-templates.md               the same list, for copying by hand
  3. <autofill folder>/kavenegar-autofill.user.js   the panel that registers them in the Kavenegar console

Every text ends with the fixed line «اتوماسیون هورمند»; the company name is a variable ({company} -> %token10).
Run:  python tools/kavenegar/gen_templates.py [folder-of-the-autofill-tool]
"""
import json
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
SIGN = 'اتوماسیون هورمند'
FA = str.maketrans('0123456789', '۰۱۲۳۴۵۶۷۸۹')
# variable -> Kavenegar parameter (%token is required in every template; only token10/token20 accept spaces)
TOKEN = {'name': '%token', 'number': '%token2', 'end': '%token3', 'company': '%token10', 'product': '%token20'}
LABEL = {'name': 'نام مشتری', 'number': 'شماره', 'end': 'تاریخ', 'company': 'نام شرکت', 'product': 'نام کالا'}


def read(rel):
    return open(os.path.join(ROOT, rel), encoding='utf-8').read()


auto_src = read('server/internal/sms/auto.go')
autos = re.findall(r'Key: "(\w+)", Title: "([^"]+)", When: "([^"]+)",\s*\n\s*Text:\s*"([^"]+)"', auto_src)
lib_src = read('web/src/lib/smsLibrary.ts')
libs = re.findall(r"key: '([\w-]+)', group: '([^']+)', label: '([^']+)', text: '([^']+)'", lib_src)

items = []  # key, name, title, when, text, auto
for key, title, when, text in autos:
    if '{company}' not in text:
        text += '\n{company}'
    items.append((key, 'hm' + key.replace('_', ''), 'خودکار: ' + title, when, text + '\n' + SIGN, True))
for key, group, label, text in libs:
    body = re.sub(r'^با سلام( و احترام)?[؛،]?\s*', '', text)
    items.append((key, 'hm' + key.replace('-', ''), group + ': ' + label, '', '{name} عزیز، ' + body + '\n{company}\n' + SIGN, False))

names = [i[1] for i in items]
assert len(set(names)) == len(names), 'template names must be unique'


def tokens(text):
    return text, [v for v in dict.fromkeys(re.findall(r'\{(\w+)\}', text))]


def to_kv(text):
    return re.sub(r'\{(\w+)\}', lambda m: TOKEN[m.group(1)], text)


# 1. Go
go = ['// Code generated by tools/kavenegar/gen_templates.py; DO NOT EDIT.', '', 'package sms', '',
      '// KVTemplates are the texts registered in the Kavenegar console under the given names. {name} {company} {number} {end} {product}', '// are sent as parameters; every text ends with the fixed line of the product.',
      'var KVTemplates = []KVTemplate{']
for key, name, title, when, text, is_auto in items:
    go.append('\t{Key: %s, Name: %s, Auto: %s, Text: %s},' % (json.dumps(key), json.dumps(name), 'true' if is_auto else 'false', json.dumps(text, ensure_ascii=False)))
go.append('}')
open(os.path.join(ROOT, 'server/internal/sms/kvtemplates_gen.go'), 'w', encoding='utf-8', newline='\n').write('\n'.join(go) + '\n')

# 2. markdown
o = ['# الگوهای کاوه‌نگار برای سامانهٔ هورمند', '',
     'هر الگو یک «نام» لاتین و یک «متن» دارد. هر دو را عیناً در «ایجاد الگوی جدید» کاوه‌نگار بگذارید (یا با ابزار خودکار ثبت کنید).', '',
     '## معنی پارامترها', '']
o += ['- %s = %s' % (TOKEN[k], LABEL[k]) for k in ('name', 'company', 'number', 'end', 'product')]
o += ['', 'آخر همهٔ متن‌ها خطِ ثابت «%s» هست و نام شرکت از پارامتر می‌آید؛ پس یک فایل برای همهٔ مشتریان کافی است.' % SIGN, '', '## الگوها', '']
for n, (key, name, title, when, text, is_auto) in enumerate(items, 1):
    o.append('### الگوی %s: %s' % (str(n).translate(FA), title))
    if when:
        o.append('زمان ارسال: ' + when)
    o += ['', 'نام الگو:', '```', name, '```', '', 'متن الگو:', '```', to_kv(text), '```', '',
          'پارامترها: ' + '، '.join('%s = %s' % (TOKEN[v], LABEL[v]) for v in tokens(text)[1]), '']
open(os.path.join(ROOT, 'sms-kavenegar-templates.md'), 'w', encoding='utf-8').write('\n'.join(o))

# 3. autofill panel
data = [{'n': str(n), 'title': title, 'name': name, 'text': to_kv(text)} for n, (key, name, title, when, text, a) in enumerate(items, 1)]
tpl = read('tools/kavenegar/autofill.template.js')
out = tpl.replace('/*DATA*/[]', json.dumps(data, ensure_ascii=False, indent=0))
dest = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, 'tools', 'kavenegar')
os.makedirs(dest, exist_ok=True)
open(os.path.join(dest, 'kavenegar-autofill.user.js'), 'w', encoding='utf-8').write(out)
print('templates:', len(items), 'ok')
